/**
 * Created by admin on 4/22/17.
 */
module.exports = Object.freeze({
    GET_STARTED : 'GET_STARTED',
    SETTING : 'SETTING',
    HELP : 'HELP',
    HELP_INPUT_FORMAT : 'HELP_INPUT_FORMAT',
    HELP_REPORT : 'HELP_REPORT',
    HELP_TRANSACTION : 'HELP_TRANSACTION',
    DELETE_TRANSACTION : 'DELETE_TRANSACTION_',
});