/**
 * Created by admin on 4/22/17.
 */

function getAmountInTextWithRegex(text, regexPattern) {
    let amount = 0;
    let result = text.trim().match(regexPattern);
    if (result) {
        let str = result[0].replace(new RegExp(',', 'gi'), '').trim();
        amount = parseFloat(str);
    }
    return amount;
}

function getAmountInTextSimple (text) {
    let regex = /(\s)(\d+(\,*))*(\d+(\.*))\d*$/igm;
    return getAmountInTextWithRegex(text, regex);
}

function getAmountInTextK (text) {
    let regex = /(\s)(\d+(\,*))*(\d+(\.*))\d*K{1}$/igm;
    return getAmountInTextWithRegex(text, regex) * 1000;
}

function getAmountInTextM (text) {
    let regex = /(\s)(\d+(\,*))*(\d+(\.*))\d*M{1}$/igm;
    return getAmountInTextWithRegex(text, regex) * 1000000;
}

module.exports = {
    checkKeyword: function (text, keywordArray) {
        if (!text || !keywordArray) {
            return false;
        }

        let keywords = Array.isArray(keywordArray) ? keywordArray : [keywordArray];

        let countTrue = 0;
        keywords.forEach(key => {
            if (typeof key === 'string' && key.toLowerCase() === text.toLowerCase()) {
                countTrue++;
            } else if (key instanceof RegExp) {
                if (!text.match(key)) {
                    countTrue++;
                }
            }
        });

        return countTrue > 0;
    },

    getRecordFromText: function (text) {
        let amount = 0;
        let name = "";
        if (text) {
            amount = getAmountInTextM(text);
            if (amount === 0) {
                amount = getAmountInTextK(text);
            }
            if (amount === 0) {
                amount = getAmountInTextSimple(text);
            }

            if (amount > 0) {
                name = text.substring(0, text.lastIndexOf(" "));

            }
        }
        return amount > 0 ? {name: name, value: amount} : null;
    }
};
/*console.log(getAmountInText("An sang 90k"))
 console.log(getAmountInText("An sang 90,000"))
 console.log(getAmountInText("An sang 90.09"))
 console.log(getAmountInText("An sang 90,000k"))
 console.log(getAmountInText("An sang 9m"))*/


// let date = moment().valueOf();
// console.log(date);
// let day = moment(date);
// console.log(day.format());
//
// var string = numeral("1,000,000.90").format('0,0.[0000]');
// console.log(string);

//insert
/*// Generate a reference to a new location and add some data using push()
 var newUser = userRef.push();

 // Get the unique key generated by push()
 var newId = newUser.key;
 newUser.set({
 date_of_birth: "June 23, 1919",
 full_name: "Alan Turing"
 }, error =>  {
 if (error) {
 console.log("Data alanisawesome could not be saved." + error);
 } else {
 console.log("Data alanisawesome saved successfully.");
 }
 });*/

//query
/*userRef.orderByChild("full_name").equalTo("Alan Turing").on("child_added", function(snapshot) {
 console.log(snapshot);
 });*/

// ref.child('user')
//     .once('value',function(snapshot) {
//         var users=[];
//         snapshot.forEach(function(childSnapshot) {
//             var item=childSnapshot.val();
//             if (/adam/i.test(item.name)) {
//                 users.push(item.userId);
//             }
//         });
//         getInvoiceTotalForUsers(users,DoSomethingWithSum);
//     });
//
//
// function getInvoiceTotalForUsers(users,callback)
// {
//     var sum=0;
//     var count=0;
//     for (var i=0; i<users.length; i++) {
//         var id=users[i];
//         ref.child('invoice')
//             .equalTo(id,'userId')
//             .orderByChild('price')
//             .startAt(10)
//             .endAt(100)
//             .once('value',function(snapshot) {
//                 snapshot.forEach(function(childSnapshot) {
//                     var item = childSnapshot.val();
//                     sum+=item.price;
//                     count++;
//                     if (count==users.length) callback(sum);
//                 });
//             });
//     }
// }